#server:
#  port: 8080 # Explicitly define the port so it's consistent
#
#spring:
#  application:
#    name: springSecFinal
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/spring_jwt
#    username: postgres
#    password: 123
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#jwt:
#  secret: supersecretkeysupersecretkey123456 # must be >= 32 chars
#  message: Logged in successfully

server:
  port: 8080

spring:
  application:
    name: springSecFinal

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_jwt}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

jwt:
  secret: ${JWT_SECRET:supersecretkeysupersecretkey123456}
  message: ${JWT_MESSAGE:Logged in successfully}

stripe:
  api:
    key: ${STRIPE_API_KEY:sk_test_51SQ6KgRTNyC3ef1LCsrHEozs5KNspvoquqkdbdelzul7OaiWuSLkEI60fvSIDjXkrVcnTXHE6fdybLy3Fesumrl800TczDkQ20}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:whsec_cfbc863d3fcf144520d1bd827463a337a0121a3f13a504875143879b6dff79df}
