server:
  port: 8080 # Explicitly define the port so it's consistent

spring:
  application:
    name: springSecFinal

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_jwt
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop # safer than create-drop (keeps data between restarts)
    show-sql: true # optional: show generated SQL in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true   # make SQL logs easier to read

jwt:
  secret: supersecretkeysupersecretkey123456 # must be >= 32 chars
  message: Logged in successfully
