server:
  port: 8080 # Explicitly define the port so it's consistent

spring:
  application:
    name: springSecFinal

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_jwt
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: supersecretkeysupersecretkey123456 # must be >= 32 chars
  message: Logged in successfully
