services:
  db:
    image: postgres:15
    container_name: server-db
    restart: always
    environment:
      POSTGRES_DB: medconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medconnect
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      STRIPE_API_KEY: sk_test_51SQ6KgRTNyC3ef1LCsrHEozs5KNspvoquqkdbdelzul7OaiWuSLkEI60fvSIDjXkrVcnTXHE6fdybLy3Fesumrl800TczDkQ20
      STRIPE_WEBHOOK_SECRET: whsec_cfbc863d3fcf144520d1bd827463a337a0121a3f13a504875143879b6dff79df
      JWT_SECRET: "supersecretkeysupersecretkey123456"
      JWT_MESSAGE: "Login Successful"
    depends_on:
      - db
    ports:  
      - "8080:8080"
#      - "5005:5005"   # NEWPORT FOR DEBUG

volumes:
  db_data:
